feat: adding module structure
instantstack/terraform-aws-budgets pull request #1
Opened 2024-05-02 15:01 UTC by Ian-Soares

2024-05-08 18:56 UTC, brunordias commented
@Ian-Soares precisamos adicionar as tags nos recursos do budgets.
espere um var.tags e coloque as tags em todos os recursos que suportarem.

2024-05-08 18:57 UTC, brunordias requested changes
adicione tags a todos os resources que suportem.

2024-05-09 14:55 UTC, brunordias requested changes

2024-05-09 14:55 UTC, brunordias commented on README.md
> +  source  = "instantstack/budgets"
@Ian-Soares aqui o source deve ficar `instantstack/budgets/aws`

2024-05-09 15:43 UTC, Ian-Soares commented on README.md
> +  source  = "instantstack/budgets"
Feito!

2024-05-09 16:12 UTC, merged